# Generated by Django 5.0 on 2023-12-14 21:06

import articles.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=20, validators=[articles.validators.validate_topic, django.core.validators.RegexValidator('^[a-zA-Zà-ù0-9 \\-]*$')])),
                ('subheading', models.CharField(max_length=255, validators=[articles.validators.validate_subheading, django.core.validators.RegexValidator('^[a-zA-Zà-ù0-9 ,.\\-]*$')])),
                ('title', models.CharField(max_length=60, validators=[articles.validators.validate_title, django.core.validators.RegexValidator('^[a-zA-Zà-ù0-9 ,.\\-]*$')])),
                ('body', models.TextField(validators=[articles.validators.validate_body])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
