# Generated by Django 5.0 on 2023-12-08 15:56

import articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(validators=[articles.validators.validate_body]),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, validators=[articles.validators.validate_title]),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(max_length=50, validators=[articles.validators.validate_topic]),
        ),
    ]
