# Generated by Django 5.0 on 2023-12-12 08:18

import articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_user_article_author_alter_article_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subheading',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[articles.validators.validate_subheading]),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=1000, validators=[articles.validators.validate_body]),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=60, validators=[articles.validators.validate_title]),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(max_length=20, validators=[articles.validators.validate_topic]),
        ),
    ]
