# Generated by Django 5.0 on 2023-12-20 13:12

import articles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subheading',
            field=models.CharField(max_length=255, validators=[articles.validators.validate_subheading, django.core.validators.RegexValidator('^[a-zA-Zà-ù0-9 :,.\\-]*$')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=60, validators=[articles.validators.validate_title, django.core.validators.RegexValidator('^[a-zA-Zà-ù0-9 :,.\\-]*$')]),
        ),
    ]
