# Generated by Django 5.0 on 2023-12-12 09:06

import articles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_subheading_alter_article_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(validators=[articles.validators.validate_body]),
        ),
        migrations.AlterField(
            model_name='article',
            name='subheading',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[articles.validators.validate_subheading, django.core.validators.RegexValidator('a-Zà-ù0-9 ,.\\-')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=60, validators=[articles.validators.validate_title, django.core.validators.RegexValidator('a-Zà-ù0-9 ,.\\-')]),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(max_length=20, validators=[articles.validators.validate_topic, django.core.validators.RegexValidator('a-Zà-ù0-9 \\-')]),
        ),
    ]
